login: &login
  adapter: postgresql
  username: postgres
  host: localhost

development:
  <<: *login
  database: css_snippets_demo_development

test:
  <<: *login
  database: css_snippets_demo_test

production:
  <<: *login
  database: css_snippets_demo_production
